[formatter.nix]
command = "alejandra"
includes = ["*.nix"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = [
  "*.ts",
  "*.tsx",
  "*.js",
  "*.jsx",
  "*.json",
  "*.css",
  "*.html",
  "*.md"
]
excludes = [
  "pnpm-lock.yaml",
  "*.svg",
  "node_modules/**",
  "dist/**",
  ".git/**"
]

[formatter.eslint]
command = "eslint"
options = ["--fix"]
includes = ["*.ts", "*.tsx", "*.js", "*.jsx"]
excludes = [
  "node_modules/**",
  "dist/**",
  ".git/**"
]
